@startuml
digraph G {
    node [shape=square];

    { rank=same; A; B }
    { rank=same; C1; C2; F }
    { rank=same; AT1; AT2 }

    A [label="Step A"];
    B [label="Step B"];

    C1 [label="Control 1"];
    C2 [label="Control 2"];

    F [label="Finished"];

    AT1 [label="Attempt Fix 1"];
    AT2 [label="Attempt Fix 2"];

    ET1 [label="End Attempt Fix 1"];
    ET2 [label="End Attempt Fix 2"];

    A -> C1 [label="1"];
    B -> C2 [label="1"];

    C1 -> B [label="0.7"];

    C1 -> AT1 [label="0.3  "];
    AT1 -> C1 [label="0.5  "];
    AT1 -> ET1 [label="0.5  "];
    ET1 -> C1 [label="1  "];

    C2 -> AT2 [label="0.3  "];
    AT2 -> C2 [label="0.8  "];
    AT2 -> ET2 [label="0.2  "];
    ET2 -> C2 [label="1  "];

    C2 -> F [label="0.7"];

    F -> F [label="1"];
}
@enduml